config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :galleries
  end
  get 'realizacje', to: 'galleries#index',     as: :realizations
  get 'cennik',     to: 'static_pages#price', as: :price

  match ':controller(/:action(/:id))', :via => [:get, :post]

  root 'static_pages#home'

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/gallery.rb
class Admin::Gallery < ActiveRecord::Base
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

                                                                   # Wybieram layouts
  before_action :authenticate                                                     # Uwiezytelniam uzytkownika, czyli nikt nie ma wstepu do panelu admina, chyba ze zna login i haslo

  def authenticate                                                                # I tu jest nasze uwiezytelnienie uzytkownikow
    authenticate_or_request_with_http_basic 'Podaj hasło!' do |name, password|
      name == 'dave' && password == 'secret'
    end
  end

end

app/controllers/admin/galleries_controller.rb
class Admin::GalleriesController < Admin::BaseController
  before_action :set_admin_gallery, only: [:show, :edit, :update, :destroy]

  # GET /admin/galleries
  # GET /admin/galleries.json
  def index
    @admin_galleries = Admin::Gallery.all
  end

  # GET /admin/galleries/1
  # GET /admin/galleries/1.json
  def show
  end

  # GET /admin/galleries/new
  def new
    @admin_gallery = Admin::Gallery.new
  end

  # GET /admin/galleries/1/edit
  def edit
  end

  # POST /admin/galleries
  # POST /admin/galleries.json
  def create
    @admin_gallery = Admin::Gallery.new(admin_gallery_params)

    respond_to do |format|
      if @admin_gallery.save
        format.html { redirect_to @admin_gallery, notice: 'Gallery was successfully created.' }
        format.json { render :show, status: :created, location: @admin_gallery }
      else
        format.html { render :new }
        format.json { render json: @admin_gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/galleries/1
  # PATCH/PUT /admin/galleries/1.json
  def update
    respond_to do |format|
      if @admin_gallery.update(admin_gallery_params)
        format.html { redirect_to @admin_gallery, notice: 'Gallery was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_gallery }
      else
        format.html { render :edit }
        format.json { render json: @admin_gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/galleries/1
  # DELETE /admin/galleries/1.json
  def destroy
    @admin_gallery.destroy
    respond_to do |format|
      format.html { redirect_to admin_galleries_url, notice: 'Gallery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_gallery
      @admin_gallery = Admin::Gallery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_gallery_params
      params.require(:admin_gallery).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def index
    @admin_galleries = Admin::Gallery.all
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def price
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/galleries/_form.html.erb
<%= form_for(@admin_gallery) do |f| %>
  <% if @admin_gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_gallery.errors.count, "error") %> prohibited this admin_gallery from being saved:</h2>

      <ul>
      <% @admin_gallery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/galleries/edit.html.erb
<h1>Editing Admin Gallery</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_gallery %> |
<%= link_to 'Back', admin_galleries_path %>

app/views/admin/galleries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admin Galleries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_galleries.each do |admin_gallery| %>
      <tr>
        <td><%= admin_gallery.name %></td>
        <td><%= link_to 'Show', admin_gallery %></td>
        <td><%= link_to 'Edit', edit_admin_gallery_path(admin_gallery) %></td>
        <td><%= link_to 'Destroy', admin_gallery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gallery', new_admin_gallery_path %>

app/views/admin/galleries/new.html.erb
<h1>New Admin Gallery</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_galleries_path %>

app/views/admin/galleries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_gallery.name %>
</p>

<%= link_to 'Edit', edit_admin_gallery_path(@admin_gallery) %> |
<%= link_to 'Back', admin_galleries_path %>

app/views/galleries/index.html.erb
<div id="main-controler">
<div class="galeries">




  <div class="single-col galeria_room">
    <h3>Galeria</h3>

    <div class="container">
      <ul>




        <li><a class="example-image-link" href="<%= image_url('owl_slider/os2.jpg') %>" data-lightbox="roadtrip" >
          <img src="<%= asset_url('owl_slider/os2.jpg') %>" width="80" height="80" alt="jeden" ></a></li>
        <li><a class="example-image-link" href="<%= image_url('owl_slider/os2.jpg') %>" data-lightbox="roadtrip" >
          <img src="<%= asset_url('owl_slider/os2.jpg') %>" width="80" height="80" alt="dwa" ></a></li>
        <li><a class="example-image-link" href="<%= image_url('owl_slider/os3.jpg') %>" data-lightbox="roadtrip" >
          <img src="<%= asset_url('owl_slider/os3.jpg') %>" width="80" height="80" alt="trzy" ></a></li>
        <li><a class="example-image-link" href="<%= image_url('owl_slider/os6.jpg') %>" data-lightbox="roadtrip" >
          <img src="<%= asset_url('owl_slider/os6.jpg') %>" width="80" height="80" alt="cztery" ></a></li>



        <li><a class="example-image-link" href="<%= asset_url('owl_slider/os2.jpg') %>" data-lightbox="roadtrip" >
          <img src="<%= asset_url('owl_slider/os2.jpg') %>" width="80" height="80" alt="jeden" ></a></li>
        <li><a class="example-image-link" href="<%= asset_url('owl_slider/os2.jpg') %>" data-lightbox="roadtrip" >
          <img src="<%= asset_url('owl_slider/os2.jpg') %>" width="80" height="80" alt="dwa" ></a></li>
        <li><a class="example-image-link" href="<%= asset_url('owl_slider/os3.jpg') %>" data-lightbox="roadtrip" >
          <img src="<%= asset_url('owl_slider/os3.jpg') %>" width="80" height="80" alt="trzy" ></a></li>
        <li><a class="example-image-link" href="<%= asset_url('owl_slider/os6.jpg') %>" data-lightbox="roadtrip" >
          <img src="<%= asset_url('owl_slider/os6.jpg') %>" width="80" height="80" alt="cztery" ></a></li>


        <!--
        <a href="<%= asset_url('owl_slider/os2.jpg') %>" data-lightbox="roadtrip" title="My caption">image #1</a>
        <a href="<%= asset_url('owl_slider/os3.jpg') %>" data-lightbox="roadtrip">image #2</a>
        <a href="<%= asset_url('owl_slider/os3.jpg') %>" data-lightbox="roadtrip">image #3</a>
        <a href="<%= asset_url('owl_slider/os6.jpg') %>" data-lightbox="roadtrip">image #4</a>


        <a class="example-image-link"
        href="<%= asset_url('owl_slider/os2.jpg') %>" data-lightbox="example-set"
        data-title="Click the right half of the image to move forward"><img class="example-image"
                                                                            src="<%= asset_url('owl_slider/os2.jpg') %>" alt=""/> </a>
        <a class="example-image-link"
           href="<%= asset_url('owl_slider/os3.jpg') %>" data-lightbox="example-set"
           data-title="Click the right half of the image to move forward"><img class="example-image"
                                                                               src="<%= asset_url('owl_slider/os2.jpg') %>" alt=""/> </a>

        <a class="example-image-link"
           href="<%= asset_url('owl_slider/os6.jpg') %>" data-lightbox="example-set"
           data-title="Click the right half of the image to move forward"><img class="example-image"
                                                                               src="<%= asset_url('owl_slider/os2.jpg') %>" alt=""/> </a>

        <a class="example-image-link"
           href="<%= asset_url('owl_slider/os2.jpg') %>" data-lightbox="example-set"
           data-title="Click the right half of the image to move forward"><img class="example-image"
                                                                               src="<%= asset_url('owl_slider/os2.jpg') %>" alt=""/> </a>

        -->


        <h3>A Four Image Set</h3>
        <div>
          <a class="example-image-link" href="http://lokeshdhakar.com/projects/lightbox2/images/image-3.jpg" data-lightbox="example-set" data-title="Click the right half of the image to move forward."><img class="example-image" src="http://lokeshdhakar.com/projects/lightbox2/images/thumb-3.jpg" alt=""/></a>
          <a class="example-image-link" href="http://lokeshdhakar.com/projects/lightbox2/images/image-4.jpg" data-lightbox="example-set" data-title="Or press the right arrow on your keyboard."><img class="example-image" src="http://lokeshdhakar.com/projects/lightbox2/images/thumb-4.jpg" alt="" /></a>
          <a class="example-image-link" href="http://lokeshdhakar.com/projects/lightbox2/images/image-5.jpg" data-lightbox="example-set" data-title="The next image in the set is preloaded as you're viewing."><img class="example-image" src="http://lokeshdhakar.com/projects/lightbox2/images/thumb-5.jpg" alt="" /></a>
          <a class="example-image-link" href="http://lokeshdhakar.com/projects/lightbox2/images/image-6.jpg" data-lightbox="example-set" data-title="Click anywhere outside the image or the X to the right to close."><img class="example-image" src="http://lokeshdhakar.com/projects/lightbox2/images/thumb-6.jpg" alt="" /></a>
        </div>
        </section>




      </ul>
    </div>
  </div>
</div>



<div class="our-services2">
</div>
</div>

app/views/layouts/_footer.html.erb
<!-- Stopka -->
<footer>
  <div class="footer-main">
    <div class="container">
      <!-- Social -->
      <div class="single-col">
        <h3>O nas</h3>
        <p>
          Na nasze usługi dajemy
          dwuletnią gwarancję. Wszelkie prace wykonujemy
          z najwyższa starannością.
        </p>
        <ul class="footer-social">
          <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
          <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
          <li><a href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
          <li><a href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a href="#"><i class="fa fa-rss"></i></a></li>
        </ul>
      </div>
      <!-- Nasz blog -->
      <div class="single-col our-blog">
        <h3>Nasz blog</h3>
        <ul>
          <li>
            <h4><a href="">Uis consequat augue dui nonm non.</a></h4>
            <span class="post-date">18 luty 2015</span>
          </li>
          <li>
            <h4><a href="">Uis consequat augue augue dui non.</a></h4>
            <span class="post-date">2 Styczeń 2015</span>
          </li>
          <li>
            <h4><a href="">Uis consequat augue dui abejnon.</a></h4>
            <span class="post-date">3 Maj 2014</span>
          </li>
        </ul>
      </div>
      <!-- Galeria -->
      <div class="single-col footer-gallery">
        <h3>Galeria</h3>
        <ul>
          <li><a href="<%= realizations_path%>"><img src="<%= asset_path('galeria2/fotolia_lampka.jpg') %>" alt=""></a></li>
          <li><a href="<%= realizations_path%>"><img src="<%= asset_path('galeria2/fotolia_swiecznik.jpg') %>" alt=""></a></li>
          <li><a href="<%= realizations_path%>"><img src="<%= asset_path('galeria2/fotolia_home_poduszka.jpg') %>" alt=""></a></li>
          <li><a href="<%= realizations_path%>"><img src="<%= asset_path('galeria2/fotolia_dom_arch.jpg') %>" alt=""></a></li>
          <li><a href="<%= realizations_path%>"><img src="<%= asset_path('galeria2/fotolia_stolik_kwiaty.jpg') %>" alt=""></a></li>
          <li><a href="<%= realizations_path%>"><img src="<%= asset_path('galeria2/fotolia_home_sweet.jpg') %>" alt=""></a></li>
        </ul>
      </div>
      <!-- Linki -->
      <div class="single-col more-links">
        <h3>Linki</h3>
        <ul>
          <li><a href="#">Strefa </a></li>
          <li><a href="#">Facebook</a></li>
          <li><a href="#">Google</a></li>
          <li><a href="#">Inne</a></li>
        </ul>
      </div>
    </div>
  </div>
  <!-- copyright -->
  <div class="copyright">
    <div class="container">
      <p>Copyright 2016 © <a href="">www.google.pl</a></p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- glowny kontener -->
<div id="main-container">

  <!-- Nawigacja -->
  <header>
    <nav>
      <div class="container">
        <div class="navbar">
          <div class="nav-logo animated bounce">      <!-- z klasą infinite bedzie nasza ikona animowac sie w sposob nieskaczony a bounce to nasze skakanie ikony -->
            <a href=""><img src="<%= asset_path('logo.png') %>" alt="logo" width="50"></a>
          </div>
          <div class="main-menu-content">
            <ul id="main-menu">
              <li><a href="/static_pages/home" class="menu-link-active">Start</a></li>
              <li><a href="">Opinie</a></li>
              <li><a href="">Portfolio</a></li>
              <li><a href="">Sklep</a></li>
              <li><a href="">Współpraca</a></li>
              <li><a href="">Kontakt</a></li>
              <li><a> <%= link_to 'Cennik', price_path %> </a></li>
              <li><a> <%= link_to 'Galeria' , realizations_path %> </a></li>
              <li><a href=""> <i class="fa fa-search"></i> </a> </li>
            </ul>
          </div>
          <!-- menu mobilne -->
          <div id="attach-mobile-menu">
          </div>
        </div>
      </div>
    </nav>
  </header>
</div>


<script>
  $(document).ready(function(){
    /* menu mobilne */
    $('#main-menu').slicknav({
      prependTo: '#attach-mobile-menu',
      label: ''                           /* label: ''  USOWAMY NAPIS MENU Z ETYKITY */
    });

    /* odliczanie */
    $('.timer').countTo();                // I tutaj dajmy nasze odliczanie  z naszeg pluginu - podpinam sie do klasy timer i wywoluje funkcji countTo



    /* YTPlayer */
    $('.player').YTPlayer();      //  Musze sie odwolac do tego elementu do ktorego bedzie wywylywany nasz player


    // Tu mam pogladowy skrypt
    /* viewport */
    $('.our-team').viewportChecker({      // Zwracamy uwage na wielkosc liter   Tutaj bedziemy mieli nasza klase
      classToAdd: 'animated slideInLeft',        // Tutaj dodamy nasza animiacjie (opcja ktora nas interesuje powinna dodawac klase  ( tutaj znajduje sie lista dostepnych opcji: https://github.com/dirkgroenen/jQuery-viewport-checker)
      repeat: true                        // Powtarzanie kiedy pojawi sie w viewporcie
    });                                   // Nas interesuje jedna czyli classToAdd: oraz element ktory wygeneruje nam animacje
                                          // animated - to klasa dodana w naszym laytsie
                                          // a swing - to dostepna animacja z strony : https://daneden.github.io/animate.css/
                                          // CZYLI - TE DWIE KLASY ZOSTANA DODANE DO NASZEJ KLASY ALE DOPIERO WTEDY KIEDY ZOSTANIE ZALOADOWANY DO VIEWPORTU

/*
    $('.opinions').viewportChecker({           // Fack - ale zajebioza
      classToAdd: 'animated slideInRight'
    });
*/

    /* viewport */
    $('*[data-animate]').addClass('hide').each(function(){            // Za pomocą jQery odwolam sie do wszystkich elementow data-animate na stronie i dodam do niej domieszke hide-ukryj-domieszka i przeliteruje petlą po nich
      $(this).viewportChecker({                                       // na kazdym elemencie (this) wywolam nasz viewportChecker
        classToAdd: 'show animated ' + $(this).data('animate'),       // i na kazdym elemencie spelniajacym nasze kryterium dodamy klse-domieszke-show + oprocz niej musze dodac nasza animiacjie
        classToRemove: 'hide',                                        // i WAZENE musimy takze usunac klase
        offset: 200                                                   // oraz dodam opuznienie 1/5sekundy
      });
    });
  });




  $('#main-container').imagesLoaded(function () {   /* I tutaj skorzystamy z naszego gemu do ladowania obrazkow przed reszta innych rzeczy - dzieki temu nie bedzie marginesu po prawej stronie widocznego np.w chromie */
    /* glowny slider */
    $('#main-slider').bxSlider({
      mode: 'fade',
      auto: true,
      controls: true,
      pager: false
    });

    /* Slider opinie */                   // Musimy go jednak tutaj wywolac poniewaz ucinal nam tekst
    $('#opinions-slider').bxSlider({      // I na naszym id wywolamy naszą funcjie
      mode: 'vertical',                   // vertical oznacza ze sliajdy bedą przeskakiwaly pionowo
      auto: true,                         // automatyczne zmiany slajdow
      controls: false,                    // Wylanczam kontrolki - nie potrzeba nam ich
      pager: false                        // bez mozliwosci zmiany recznej
    });

    $('#portfolio-carousel').owlCarousel({       /* Najpierw wysolajmy nasze elementy tego slidera */
      autoPlay: 10000,                           // Automatyczne przewijanie slidow czyli 10sek
      items: 3,                                  // Przewijanie slidow - maxymalinie 3
      itemsDesktopSmall: [1199, 2],              //  Tu okreslimy sobie szerokosc dla takich srednich rozmiarow (1199-napierw szerokosc,a potem ponizej tej szerokosci bedą ladwoane tylko dwa zdjecia- zerknijmy na strone i tam mamy duzo wlasciwosci :http://owlgraphic.com/owlcarousel/#customizing
      itemsTablet: [768, 1]
    });




  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Fonty Google -->
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,400italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <!-- Wchodzimy na strone google fonts, klikamy quick use, zaznaczamy normal 400 i normal italic i kopujemy link poniżej
   i wklejamy go do naszej apki
   -->
  <!-- Oraz drugi font lato -wpisujemy i tylko normal400 -->


  <!--
  <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
   dzieki temu mamy mozliwosc dodania ikonki wyszukiwania
   ale my uzylismy gemu font-awesome-sass -->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>



  <!--
  Znacznik powyżej dla użądzen mobilnych
  chodzi o to - ze rozmair roboczego obszaru ma sie dostosowac do uządzenie i początkowa szerokość to 1
  -->


  <!-- jQuery -->
  <!--MENU MENU MENU  -->
  <!-- Ten skrypt jest nam potrzebny do naszego mobilnego menu - dzieki niemu bedziemy mieli
   mozliwosc zastostowania rozwiajanego menu -->
  <!-- <script src="http://code.jquery.com/jquery-1.11.2.min.js"></script>  -->   <!-- Bardzo wazne najpierw podpinamy wlasciwą biloteke a dopiero puzniej dodatki --|>
  <!-- mobilne menu --> <!-- Wchodzimy na strne http://slicknav.com/ pobieramy  i kopiujemy 4 pliki  jquery.slicknav.js i slicknav.scss core.scss theme.scss i wklejamy odpowiednio -->
  <!-- <script src="http://code.jquery.com/jquery-1.9.0rc1.js"></script> -->

  <script src="../../assets/javascripts/jquery.slicknav.min.js"></script>

  
  /<!-- <link rel="stylesheet" href="../../assets/stylesheets/style_new/slick/slicknav.scss">  -->



  <!-- Odliczanie -->
  <!-- 26.Statystiki_skrypt_countTo -->
  <!-- Podepnijmy standardowo nasz skrypt ze strony https://github.com/mhuggins/jquery-countTo/blob/master/jquery.countTo.js-->
  <script src="../../assets/javascripts/jquery.countTo.js"></script>


  <!-- 39.Bibloteka_Animate_Skrypt_Viewport_checker -->
  <!-- Podpinamy nasza bibloteke  -->
  <script src="../../assets/javascripts/jquery.viewportchecker.js"></script>

  <!--  Sekcja Wideo -->
  <!-- YTPlayer -->
  <!--  43.Plugin_Wideo_cz.1 -->
  <script src="../../assets/javascripts/jquery.mb.YTPlayer.min.js"></script>






  <!-- Sekcja Gallery -->
  <link rel="stylesheet" href="../../assets/stylesheets/lightbox.scss">
  <script src="../../assets/javascripts/lightbox.min.js"></script>


</head>
<body>

  <%=  render 'layouts/header' %>

<%= yield %>

  <%= render 'layouts/footer' %>

</body>
</html>